### PR TITLE
Color Problem in /news

### PR DESCRIPTION
**Pull request by Techno3600**
Just check the pull request, the &c should be &4.

# Pull Template

### CODE REVIEW

**Comment by Techno3600** [comment]
So does that means it is getting merged @WheezyGold7931 ?

**Comment by WheezyGold7931** [comment]
@Techno3600 I've reviewed it

**Comment by xMRENDERMAN** [comment]
~ New request review

**Comment by Techno3600** [comment]
Good point, I’ll make those changes when I have time, also the color in /news’ commands might be dark red to correspond with the Admin rank, are you sure that the commands should be &6 or &4? I personally like the &6 for /news so if there is no objection I’ll make it &6.

**Comment by WheezyGold7931** [comment]
Addressed and added

**Pull request closed without merging**
