### PR TITLE
Adding Slight Fly Speed Increase To Players on "/gm"

### PR DESCRIPTION
**Pull request by Techno3600**
This is a super small change that makes the "/gm" command more authentic to Mineplex. When doing "/gm" the player's fly speed gets updated to go a little faster and when the player is put back into survival the fly speed gets reset.

Thanks
Techno

### CODE REVIEW

**Comment by xLengoBug5** [comment]
This feature is not on MP and will most likely not be added to MCR. Yet, if you want to keep this pull request open a Developer could check it and maybe consider it.

-Lengo

**Comment by Nathan100YT** [comment]
Hey, adding on to what Lengo said, I don't think this is a feature in Mineplex, if there is any proof of this feature that would be great, again I will still leave this open for a developer to check.

**Comment by Techno3600** [comment]
Hey Guys,

Responding to what @xLengoBug5 said: I need a specification to why this could not be added to the remake.

Responding to what @Nathan100YT said: Check SamtioD's videos when he was an admin (he went into creative mode once and you could see the increased speed). Check any YouTube videos of people seeing admins in lobbies, they will show them flying at an increased speed. Lastly, I have seen an 3 admins, and 2 leaders, I saw a few flying in creative mode and you could see the increased speed.

Thanks
Techno

**Comment by xMRENDERMAN** [comment]
Hey

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Techno3600** [comment]
What?

**Comment by Techno3600** [comment]
@WheezyGold7931 , are you going to review it?

**Comment by Techno3600** [comment]
Awesome, thanks!

**Comment by Techno3600** [comment]
Hey @WheezyGold7931,
I checked the code and saw that I made a pretty dumb mistake, can you please re-check it? Don’t want to bug up MP Core.

**Comment by xLengoBug5** [comment]
You guys could ask NaiculS about this. He is a Mod on the real Mineplex and can probably answer this question. And to what I know the flight on /gm is a optional thing in the exclusive section of /prefs. Replacing Invisibility & Flight.

**Comment by Techno3600** [comment]
I thought /gm was exclusive to admins these days, a few days ago I asked a MapLead if he could /gm and he said he couldn’t, the difference from /gm and the Flight/Invis is that you can’t break block s with the Exclusives Preferences, but with /gm you can.

**Comment by WheezyGold7931** [comment]
Only a thing in build servers, closing pull

**Pull request closed without merging**
