### PR TITLE
Track list in-game

### PR DESCRIPTION
**Pull request by NaiculS**
# Pull Template

## What does this pull request add?
A list of titles in game
## Does this fix any issues? If so list the issue number.
no
## Have you tested the code subject in this pull?
no

### CODE REVIEW

**Comment by xMRENDERMAN** [comment]
Is this in mineplex?

**Comment by NaiculS** [comment]
No, but as we don’t have the title book we need some way in game for everyone to see all the different titles.

**Comment by xMRENDERMAN** [comment]
Hm.. there’s probably a way to make it in skript.

**Comment by xMRENDERMAN** [comment]
Apparently it can be done with skellet

**Comment by NaiculS** [comment]
Wheezy said he didn’t do it because it was so hard, this is a much easier alternative

**Comment by xMRENDERMAN** [comment]
I might try giving it a go tomorrow.

**Comment by xMRENDERMAN** [comment]
(Seems like I’ll be at it a while :P)

**Comment by xMRENDERMAN** [comment]
~Posted Review

**Comment by WheezyGold7931** [comment]
Denied

**Comment by xMRENDERMAN** [comment]
> Have you tested the code subject in this pull?
> no
Just pointing that out there for 
> Also I can tell you didn't test this as the message effect has nobody to send your messages to...

xD

**Comment by xMRENDERMAN** [comment]
Anyway; I agree, shouldn't use the database system.

**Pull request closed without merging**
