### PR TITLE
/updaterank Join Message Fixes

### PR DESCRIPTION
**Pull request by xMRENDERMAN**
# Pull Template

## What does this pull request add?

These changes are to remove the "Client Manager> Your rank has been updated to (rank)!" message when you join the server.

## Does this fix any issues? If so list the issue number.

1. Removes the updated rank join message

### __*FOR DEVELOPERS*__:

2. Added a new variable: {mineplex.rankload.(player)}

  This is just so it can check if the player just joined to remove the updated rank message.

## Have you tested the code subject in this pull?

Not yet but I have thoroughly kept checking the code and I believe that it *should* work.
I have also made sure that it only blocks out the join message, and not the actual /updaterank message.

### CODE REVIEW

**Comment by WheezyGold7931** [comment]
Needs another variable.
I do not think a variable would be the best choice for this, maybe try another method and re pull

**Comment by xMRENDERMAN** [comment]
Okay, I might just instead use a function and return a boolean. I'll make another pull once I find a way to do so. Thanks.

**Comment by WheezyGold7931** [comment]
A function sounds good :P

**Comment by xMRENDERMAN** [comment]
Yeah! Okay, welp gtg, cya!

**Pull request closed without merging**
