### PR TITLE
Updates to ranks

### PR DESCRIPTION
**Pull request by NaiculS**
# Pull Template

## What does this pull request add?
It should change /updaterank to /rank while removing Jr. Dev and C. Mod as those are no longer ranks
## Does this fix any issues? If so list the issue number.
No, it's more of an update to make it more accurate.
## Have you tested the code subject in this pull?
Nope, and I probably messed up a lot/missed some things as I've never done this before, hopefully this still helps though.

### CODE REVIEW

**Comment by xMRENDERMAN** [comment]
Isn’t Jr. Dev still a rank, but just given to part-time developers for Mineplex?

**Comment by NaiculS** [comment]
Nope, it and C. Mod have been removed entirely. C. Mods and CMAs all have sub ranks but only in clans.

**Comment by Techno3600** [comment]
Yep

**Comment by WheezyGold7931** [comment]
I have already converted over to /rank (Much better lmao) and I will be keeping the ranks as removing ranks is not a good idea.

**Pull request closed without merging**
