### PR TITLE
Gamemode Changes

### PR DESCRIPTION
**Pull request by xMRENDERMAN**
This adds in missing messages and also fixes some messages such as the default skript offline player message with the mineplex offline player message.

### CODE REVIEW

**Comment by Torksi** [comment]
Are you sure that is correct now?

**Comment by xMRENDERMAN** [comment]
@Torksi Yes

**Comment by xMRENDERMAN** [comment]
Oops

**Comment by xMRENDERMAN** [comment]
I closed it...?

**Comment by Keyloren** [comment]
Yes

**Comment by WheezyGold7931** [comment]
Pull Request has been closed due to conflicts with main branch

**Comment by xMRENDERMAN** [comment]
I added a second argument for the invalid arguments message to show :P

**Pull request closed without merging**
